version: "3.8"
# un nouveau commentaire
volumes:
  mariaspoti: #déclaration du volume pour la base

services:

  # container de bdd
  spotibase: #nom de service
    container_name: basespoti
    image: mariadb:latest
    ports:
      - '3309:3306'
    volumes:
      - mariaspoti:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: spotiadmin
      MYSQL_DATABASE: spoti
      MYSQL_USER: spotiuser
      MYSQL_PASSWORD: spotiuser

  # container php
  spotiphp:
    container_name: phpspoti
    build:
      context: ./php
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: UTC
    volumes:
      - ./app:/var/www/html
    depends_on:
      - spotibase

  # service node
  spotinode:
    tty: true
    container_name: nodespoti
    build:
      context: ./node
    volumes:
      - ./app:/var/www/html
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - spotiphp

  # server web
  spotinginx:
    container_name: nginxspoti
    image: nginx:stable-alpine
#    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: UTC
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx/
    depends_on:
      - spotiphp
      - spotibase
      - spotinode